### ISSUE TITLE
zen fails to load when attempting to create `plugged` dir

### ISSUE THREAD

**Issue by veirus** [prakashdanish/vim-zen#1]
OS: Win8.1 x64
`:ve`:  8.0.1839
On Vim start:
```vim
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function zen#init:
line   15:
E739: Cannot create directory: C:\Users\User.vim/plugged
Error detected while processing C:\Users\User\.vim\vimrc:
line    7:
E492: Not an editor command: Plugin 'tpope/vim-rsi'
```
Possible reason - *missing slash* in zen.vim line #24:
```vim
        if !isdirectory($HOME . '.vim/plugged')
            call mkdir($HOME . '.vim/plugged')
        endif
```

**Comment by danishprakash** [comment]
@veirus I haven't tested this on windows due to having no access to one. Will try to figure this out as soon as I get my hands on one. Although, If you could test the possible solution you stated and send a pr, It'll be great.

**Comment by hegga** [comment]
Same issue on MacOS High Sierra
:ve
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 13 2018 20:06:26)
macOS version

```
$ vim
Error detected while processing function zen#init:
line   15:
E739: Cannot create directory: /Users/[redacted].vim/plugged
Error detected while processing /Users/[redacted]/.vimrc:
```

**Comment by cookiengineer** [comment]
@prakashdanish I actually had the same problem and I created a pull request here: https://github.com/prakashdanish/vim-zen/pull/2

Afterwards it is working perfectly on Arch Linux.

**Comment by danishprakash** [comment]
@veirus could you try again and revert back after the latest hotfix? I might not be able to get hold of a windows machine after all. It's working on Unix based systems though.

**Comment by veirus** [comment]
@prakashdanish sorry for a long delay. Original issue is gone with new version, however new arised.
.vimrc:
```vim
if &cp | se nocp | endif
set rtp^=~\.vim,~\.vim\after
let &packpath = &runtimepath

" begin section
call zen#init()
Plugin 'junegunn/goyo.vim' 
Plugin 'https://github.com/prakashdanish/vimport'
```

`ZenInstall` output:
```vim
vim-zen - [ Installation finished!	|	 Time: 0.125 ]
===================================================

[x] goyo.vim: [ERROR] '{' is not recognized as an internal or external command, operable program or batch file.
[x] vimport: [ERROR] '{' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by cookiengineer** [comment]
@veirus Are you using VIM inside CMD and not inside bash? Do you have python3 installed on your system and does it correctly work?

**Comment by veirus** [comment]
@cookiengineer absolutely negative. It's gVim 8.0.1839 x64 on Win 8.1 x64. Python installed and working well though. I just tried `vim-zen` out of interest, so if there's no support for Windows that's not a problem.

**Comment by danishprakash** [comment]
@veirus I'm working on this issue, in the meantime can you please create a new issue, it'll be easier for others to identify potential issues or issues that have been fixed.
