### ISSUE TITLE
Module `Queue` not found on Python 3

### ISSUE THREAD

**Issue by kamnxt** [prakashdanish/vim-zen#5]
Doesn't seem to work with multiple plugins in Python 3, since Queue cannot be imported.

**Comment by danishprakash** [comment]
@kamnxt could you please post the log?

**Comment by nhymxu** [comment]
Seem like problem because python 3 using queue, not Queue.
I'm using vim version from jonathonf ppa.

And commands package not found on python3

**Comment by danishprakash** [comment]
@nhymxu according to this [question](https://stackoverflow.com/questions/29687837/queue-importerror-in-python-3/29688081#29688081) over on SO, the name of the package are `queue` in python2 and `Queue` in python3. This certainly seems to be the issue.

**Comment by nhymxu** [comment]
@prakashdanish and other problem is: 

> Deprecated since version 2.6: The commands module has been removed in Python 3. Use the subprocess module instead.

**Comment by danishprakash** [comment]
@nhymxu you're right, I somehow skipped that. Could you open another issue for that, will look into it.
